version: '3.8'

services:
  zipcode-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SKIP_CLEAN=true
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/zipcodedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - ZIPCODE_API_URL=https://viacep.com.br
    depends_on:
      - postgres
    networks:
      - zipcode-network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=zipcodedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zipcode-network

volumes:
  postgres_data:

networks:
  zipcode-network:
    driver: bridge