services:
  zipcode-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/zipcodedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword
      - ZIPCODE_API_URL=https://viacep.com.br
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - zipcode-network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=zipcodedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d zipcodedb"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - zipcode-network

volumes:
  postgres_data:

networks:
  zipcode-network:
    driver: bridge