app:
  external-api:
    url: ${ZIPCODE_API_URL:https://viacep.com.br}

spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/zipcodedb
    username: zipuser
    password: zippassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  level:
    br.com.silvestre.zipcodeSearch: INFO